export const OVERVIEW_DATA = [
    {
        id: "laptop",
        title: "Laptops\nBuilt for More",
        text: "Powerful. Reliable. Designed for creators, professionals and visionaries. Corneli laptops combine performance, precision and timeless design.",
    },
    {
        id: "desktop",
        title: "Desktops\nMade to Perform",
        text: "Engineered for demanding work. Corneli desktops deliver uncompromising performance, refined design and the power to handle what comes next.",
    },
    {
        id: "monitor",
        title: "Monitors\nSee More Clearly",
        text: "Precise. Immersive. Designed for modern workspaces. Corneli monitors bring clarity, detail and elegant design to every environment.",
    },
    {
        id: "accessories",
        title: "Accessories\nComplete Your Setup",
        text: "Thoughtfully designed essentials for your workspace. Corneli accessories combine functionality, simplicity and timeless design.",
    },
];

export const DESKTOPS = [
    {
        id: 1,
        name: "CORNELI Forge X",
        category: "desktops",
        type: "Workstation",
        price: 2499,
        colors: ["black", "gray"],
        image: "./assets/images/desktops/forge-x.jpg",
    },
    {
        id: 2,
        name: "CORNELI Core S",
        category: "desktops",
        type: "Performance Desktop",
        price: 1899,
        colors: ["black", "silver"],
        image: "./assets/images/desktops/core-s.jpg",
    },
    {
        id: 3,
        name: "CORNELI Studio Pro",
        category: "desktops",
        type: "Creator Desktop",
        price: 2199,
        colors: ["black"],
        image: "./assets/images/desktops/studio-pro.jpg",
    },
    {
        id: 4,
        name: "CORNELI Edge",
        category: "desktops",
        type: "Compact Desktop",
        price: 1399,
        colors: ["black", "gray"],
        image: "./assets/images/desktops/edge.jpg",
    },
    {
        id: 5,
        name: "CORNELI Apex",
        category: "desktops",
        type: "Gaming Desktop",
        price: 2899,
        colors: ["black"],
        image: "./assets/images/desktops/apex.jpg",
    },
];

export const LAPTOPS = [
    {
        id: 1,
        name: "CORNELI Atlas 14",
        category: "Laptops",
        type: "Ultrabook",
        price: 1299,
        colors: ["black", "gray", "silver"],
        image: "public/images/laptop.png",
    },
    {
        id: 2,
        name: "CORNELI Nova 16",
        category: "Laptops",
        type: "Performance Laptop",
        price: 1699,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 3,
        name: "CORNELI Vega 15",
        category: "Laptops",
        type: "Creator Laptop",
        price: 1499,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 4,
        name: "CORNELI Aero 13",
        category: "Laptops",
        type: "Ultra Portable",
        price: 1199,
        colors: ["champagne", "silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 5,
        name: "CORNELI Titan 17",
        category: "Laptops",
        type: "Workstation Laptop",
        price: 2199,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 6,
        name: "CORNELI Element 14",
        category: "Laptops",
        type: "Everyday Laptop",
        price: 1099,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 7,
        name: "CORNELI Flex 15",
        category: "Laptops",
        type: "Convertible Laptop",
        price: 1399,
        colors: ["black", "silver"],
        image: "public/images/laptop.png",
    },
    {
        id: 8,
        name: "CORNELI Pro 16",
        category: "Laptops",
        type: "Business Laptop",
        price: 1749,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 9,
        name: "CORNELI Summit 14",
        category: "Laptops",
        type: "2-in-1 Convertible",
        price: 1449,
        colors: ["gray", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 10,
        name: "CORNELI Essence 13",
        category: "Laptops",
        type: "Lightweight Laptop",
        price: 999,
        colors: ["silver", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 11,
        name: "CORNELI Orion 16",
        category: "Laptops",
        type: "Gaming Laptop",
        price: 1899,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 12,
        name: "CORNELI Pulse 14",
        category: "Laptops",
        type: "Student Laptop",
        price: 899,
        colors: ["gray", "black"],
        image: "public/images/laptop.png",
    },
];

export const MONITORS = [
    {
        id: 1,
        name: "CORNELI Vision 32",
        category: "monitors",
        type: "Professional Monitor",
        price: 899,
        colors: ["black"],
        image: "./assets/images/monitors/vision-32.jpg",
    },
    {
        id: 2,
        name: "CORNELI Studio 27",
        category: "monitors",
        type: "Creator Monitor",
        price: 699,
        colors: ["black", "silver"],
        image: "./assets/images/monitors/studio-27.jpg",
    },
    {
        id: 3,
        name: "CORNELI Ultra 34",
        category: "monitors",
        type: "Ultrawide Monitor",
        price: 1099,
        colors: ["black"],
        image: "./assets/images/monitors/ultra-34.jpg",
    },
    {
        id: 4,
        name: "CORNELI Frame 24",
        category: "monitors",
        type: "Everyday Monitor",
        price: 399,
        colors: ["black", "white"],
        image: "./assets/images/monitors/frame-24.jpg",
    },
    {
        id: 5,
        name: "CORNELI Apex 32",
        category: "monitors",
        type: "Gaming Monitor",
        price: 999,
        colors: ["black"],
        image: "./assets/images/monitors/apex-32.jpg",
    },
];

export const ACCESSORIES = [
    {
        id: 1,
        name: "CORNELI Type 01 Keyboard",
        category: "accessories",
        type: "Mechanical Keyboard",
        price: 149,
        colors: ["black", "white"],
        image: "./assets/images/accessories/type-01.jpg",
    },
    {
        id: 2,
        name: "CORNELI Arc Mouse",
        category: "accessories",
        type: "Wireless Mouse",
        price: 89,
        colors: ["black", "silver"],
        image: "./assets/images/accessories/arc-mouse.jpg",
    },
    {
        id: 3,
        name: "CORNELI Sound One",
        category: "accessories",
        type: "Wireless Headphones",
        price: 249,
        colors: ["black", "gray"],
        image: "./assets/images/accessories/sound-one.jpg",
    },
    {
        id: 4,
        name: "CORNELI Dock Pro",
        category: "accessories",
        type: "USB-C Dock",
        price: 179,
        colors: ["black", "silver"],
        image: "./assets/images/accessories/dock-pro.jpg",
    },
    {
        id: 5,
        name: "CORNELI Desk Hub",
        category: "accessories",
        type: "Desktop Hub",
        price: 129,
        colors: ["black"],
        image: "./assets/images/accessories/desk-hub.jpg",
    },
];