export const PRODUCTS = [
    {
        id: 1,
        name: "CORNELI Forge X",
        category: "desktops",
        type: "Workstation",
        price: 2499,
        colors: ["black", "gray"],
        image: "corneli-app/public/images/desktop.png",
    },
    {
        id: 2,
        name: "CORNELI Core S",
        category: "desktops",
        type: "Performance Desktop",
        price: 1899,
        colors: ["black", "silver"],
        image: "public/images/desktop.png",
    },
    {
        id: 3,
        name: "CORNELI Studio Pro",
        category: "desktops",
        type: "Creator Desktop",
        price: 2199,
        colors: ["black"],
        image: "public/images/desktop.png",
    },
    {
        id: 4,
        name: "CORNELI Edge",
        category: "desktops",
        type: "Compact Desktop",
        price: 1399,
        colors: ["black", "gray"],
        image: "public/images/desktop.png",
    },
    {
        id: 5,
        name: "CORNELI Apex",
        category: "desktops",
        type: "Gaming Desktop",
        price: 2899,
        colors: ["black"],
        image: "public/images/desktop.png",
    },
        {
        id: 6,
        name: "CORNELI Atlas 14",
        category: "laptops",
        type: "Ultrabook",
        price: 1299,
        colors: ["black", "gray", "silver"],
        image: "public/images/laptop.png",
    },
    {
        id: 7,
        name: "CORNELI Nova 16",
        category: "laptops",
        type: "Performance Laptop",
        price: 1699,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 3,
        name: "CORNELI Vega 15",
        category: "laptops",
        type: "Creator Laptop",
        price: 1499,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 8,
        name: "CORNELI Aero 13",
        category: "laptops",
        type: "Ultra Portable",
        price: 1199,
        colors: ["#F7E6CA", "silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 9,
        name: "CORNELI Titan 17",
        category: "laptops",
        type: "Workstation Laptop",
        price: 2199,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 10,
        name: "CORNELI Element 14",
        category: "laptops",
        type: "Everyday Laptop",
        price: 1099,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 11,
        name: "CORNELI Flex 15",
        category: "laptops",
        type: "Convertible Laptop",
        price: 1399,
        colors: ["black", "silver"],
        image: "public/images/laptop.png",
    },
    {
        id: 12,
        name: "CORNELI Pro 16",
        category: "laptops",
        type: "Business Laptop",
        price: 1749,
        colors: ["silver", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 13,
        name: "CORNELI Summit 14",
        category: "laptops",
        type: "2-in-1 Convertible",
        price: 1449,
        colors: ["gray", "black"],
        image: "public/images/laptop.png",
    },
    {
        id: 14,
        name: "CORNELI Essence 13",
        category: "laptops",
        type: "Lightweight Laptop",
        price: 999,
        colors: ["silver", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 15,
        name: "CORNELI Orion 16",
        category: "laptops",
        type: "Gaming Laptop",
        price: 1899,
        colors: ["black", "gray"],
        image: "public/images/laptop.png",
    },
    {
        id: 16,
        name: "CORNELI Pulse 14",
        category: "laptops",
        type: "Student Laptop",
        price: 899,
        colors: ["gray", "black"],
        image: "public/images/laptop.png",
    },
        {
        id: 17,
        name: "CORNELI Vision 32",
        category: "monitors",
        type: "Professional Monitor",
        price: 899,
        colors: ["black"],
        image: "public/images/content.jpg",
    },
    {
        id: 18,
        name: "CORNELI Studio 27",
        category: "monitors",
        type: "Creator Monitor",
        price: 699,
        colors: ["black", "silver"],
        image: "public/images/content.jpg",
    },
    {
        id: 19,
        name: "CORNELI Ultra 34",
        category: "monitors",
        type: "Ultrawide Monitor",
        price: 1099,
        colors: ["black"],
        image: "public/images/content.jpg",
    },
    {
        id: 20,
        name: "CORNELI Frame 24",
        category: "monitors",
        type: "Everyday Monitor",
        price: 399,
        colors: ["black", "white"],
        image: "public/images/content.jpg",
    },
    {
        id: 21,
        name: "CORNELI Apex 32",
        category: "monitors",
        type: "Gaming Monitor",
        price: 999,
        colors: ["black"],
        image: "public/images/content.jpg",
    },
        {
        id: 22,
        name: "CORNELI Type 01 Keyboard",
        category: "accessories",
        type: "Mechanical Keyboard",
        price: 149,
        colors: ["black", "white"],
        image: "public/images/accessories.png",
    },
    {
        id: 23,
        name: "CORNELI Arc Mouse",
        category: "accessories",
        type: "Wireless Mouse",
        price: 89,
        colors: ["black", "silver"],
        image: "public/images/accessories.png",
    },
    {
        id: 24,
        name: "CORNELI Sound One",
        category: "accessories",
        type: "Wireless Headphones",
        price: 249,
        colors: ["black", "gray"],
        image: "public/images/accessories.png",
    },
    {
        id: 25,
        name: "CORNELI Dock Pro",
        category: "accessories",
        type: "USB-C Dock",
        price: 179,
        colors: ["black", "silver"],
        image: "public/images/accessories.png",
    },
    {
        id: 26,
        name: "CORNELI Desk Hub",
        category: "accessories",
        type: "Desktop Hub",
        price: 129,
        colors: ["black"],
        image: "public/images/accessories.png",
    }
];